[project]
name = "lacuna"
version = "0.1.0"
description = "pretrain and finetune hf models"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.8.0",
    "datasets>=4.0.0",
    "liger-kernel>=0.6.2",
    "transformers>=4.56.0",
    "kernels>=0.9.0",
    "cut-cross-entropy[transformers]",
    "pydantic-settings>=2.10.1",
    "wandb>=0.21.2",
    "loguru>=0.7.3",
    "rich>=14.1.0",
]

[project.scripts]
pt = "lacuna.cli:pretrain"
sft = "lacuna.cli:sft"
dcp_to_hf = "lacuna.cli:dcp_to_hf"

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.11",
    "ty>=0.0.1a19",
]

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = [
    "--verbose",
    "--color=yes",
    "--tb=short",
    "--disable-warnings",
    "-ra",
    "--cov=lacuna",
    "--cov-report=term-missing",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]
cut-cross-entropy = { git = "https://github.com/axolotl-ai-cloud/ml-cross-entropy.git", rev = "c6a32c" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
