[project]
name = "lacuna"
version = "0.1.0"
description = "pretrain and finetune hf models"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "liger-kernel>=0.6.1",
    "pydantic-settings>=2.10.1",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
    "transformers>=4.55.2",
    "wandb>=0.21.1",
    "flash-attn>=2.8.3",
    "loguru>=0.7.3",
    "pyarrow>=21.0.0",
]

[project.scripts]
pt = "lacuna.cli:pretrain_main"
sft = "lacuna.cli:sft_main"

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.9",
    "ty>=0.0.1a18",
]

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = [
    "--verbose",
    "--color=yes",
    "--tb=short",
    "--disable-warnings",
    "-ra",
    "--cov=lacuna",
    "--cov-report=term-missing",
]

[tool.uv]
no-build-isolation-package = ["flash-attn"]
prerelease = "allow"
