[project]
name = "lacuna"
version = "0.1.0"
description = "pretrain and finetune hf models"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.12.9",
    "ty>=0.0.1a18",
]
