# Baseline HF

[model]
name = "Qwen/Qwen3-8B-Base"
attention = "eager"

[trainer]
steps = 50
batch_size = 1

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 10

[checkpoint]
save_dir = "benchmark_results/baseline"