# Baseline HF

[model]
name = "Qwen/Qwen2.5-0.5B"
attention = "eager" 
enable_liger = false
enable_cce = false
enable_kernelize = false

[trainer]
steps = 50

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 40

[checkpoint]
save_dir = "benchmark_results/baseline"