# Baseline HF w/ FA2

[model]
name = "Qwen/Qwen3-8B"
attention = "FA2"

[trainer]
steps = 100
batch_size = 1

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 10

[checkpoint]
save_dir = "benchmark_results/fa2"