# Baseline HF w/ SDPA

[model]
name = "Qwen/Qwen3-8B"
attention = "SDPA" 

[trainer]
steps = 50

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 10

[checkpoint]
save_dir = "benchmark_results/sdpa"