# Scenario 1: Baseline - No optimizations
# No Liger, no CCE, sdpa attention, no compile

[model]
name = "Qwen/Qwen2.5-0.5B"
attention = "SDPA" 
enable_liger = false
enable_cce = false
enable_kernelize = false

[data]
dataset_name = "keatone/TinierStories"
seq_len = 2048

[trainer]
batch_size = 8
steps = 50

[optimizer]
lr = 3e-4

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 40

[checkpoint]
save_every = 1000  # Won't trigger in 100 steps
save_dir = "benchmarks/results/baseline"

[metrics]
log_every = 10

[wandb]
enabled = false