# SDPA + compile + kernelize

[model]
name = "Qwen/Qwen3-8B"
attention = "SDPA"
kernelize = true
compile_mode = "max-autotune"

[trainer]
steps = 500
batch_size = 2

[data]
seq_len = 1024

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 10

[checkpoint]
save_dir = "benchmark_results/sdpa_compile_kernelize"