# FA2 + compile + kernelize

[model]
name = "Qwen/Qwen3-8B"
attention = "FA2"
kernelize = true
compile_mode = "max-autotune"

[trainer]
steps = 100
batch_size = 1

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 10

[checkpoint]
save_dir = "benchmark_results/fa2_compile_kernelize"