# Liger + SDPA (no compile)

[model]
name = "Qwen/Qwen2.5-0.5B"
attention = "FA2"
enable_liger = true
enable_cce = false
enable_kernelize = false

[trainer]
steps = 50

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 40

[checkpoint]
save_dir = "benchmark_results/liger_fa2"