# Liger + FA2 + compile

[model]
name = "Qwen/Qwen3-8B"
attention = "FA2"
liger = true
compile_mode = "max-autotune"

[trainer]
steps = 100
batch_size = 1

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 10

[checkpoint]
save_dir = "benchmark_results/liger_fa2_compile"