# Liger + CCE + FA3 (no compile)

[model]
name = "Qwen/Qwen3-8B"
attention = "FA3"
liger = true
cce = true

[trainer]
steps = 500
batch_size = 1

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 10

[checkpoint]
save_dir = "benchmark_results/liger_cce_fa3"