# Liger + CCE + FA2 (no compile)

[model]
name = "Qwen/Qwen3-8B"
attention = "FA3"
enable_liger = true
enable_cce = true

[trainer]
steps = 50
batch_size = 1

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 10

[checkpoint]
save_dir = "benchmark_results/liger_cce_fa3"