# Liger + CCE + SDPA (no compile)

[model]
name = "Qwen/Qwen3-8B"
attention = "SDPA"
liger = true
cce = true

[trainer]
steps = 100
batch_size = 1

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 10

[checkpoint]
save_dir = "benchmark_results/liger_cce_sdpa"