# Liger + CCE + SDPA (no compile)

[model]
name = "Qwen/Qwen3-8B"
attention = "SDPA"
enable_liger = true
enable_cce = true

[trainer]
steps = 50

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 10

[checkpoint]
save_dir = "benchmark_results/liger_cce_sdpa"