# Kernelize + CCE + SDPA + compile

[model]
name = "Qwen/Qwen3-8B"
attention = "SDPA"
kernelize = true
cce = true
compile_mode = "max-autotune"

[trainer]
steps = 500

[data]
seq_len = 2048

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 10

[checkpoint]
save_dir = "benchmark_results/kernelize_cce_sdpa_compile"