# Liger + CCE + SDPA + compile

[model]
name = "Qwen/Qwen2.5-0.5B"
attention = "SDPA"
enable_liger = true
enable_cce = true
enable_kernelize = false
compile_mode = "max-autotune"

[trainer]
steps = 50

[scheduler]
type = "wsd"
warmup_steps = 10
decay_steps = 40

[checkpoint]
save_dir = "benchmark_results/liger_cce_sdpa_compile"