[model]
name = "Qwen/Qwen2.5-0.5B"

[data]
dataset_name = "keatone/TinierStories"
split = "train"
seq_len = 2048
num_workers = 0

[trainer]
steps = 20
eval_every = 10
batch_size = 8

[optimizer]
type = "adamw"
lr = 3e-4
weight_decay = 0.1
betas = [0.9, 0.95]
grad_clip = 1.0

[scheduler]
type = "cosine"
warmup_steps = 5
min_lr_ratio = 0.1

[checkpoint]
save_every = 10
keep_latest = 2
save_dir = "weights"

[metrics]
log_every = 2