[model]
name = "Qwen/Qwen2.5-0.5B"

[data]
dataset_name = "keatone/s1K"
split = "train"
seq_len = 8192
num_workers = 0
packing = true

[trainer]
epochs = 1
eval_every = 1
batch_size = 2

[optimizer]
type = "adamw"
lr = 3e-4
weight_decay = 0.1
betas = [0.9, 0.95]
grad_clip = 1.0

[scheduler]
type = "cosine"
warmup_steps = 100
min_lr_ratio = 0.1

[checkpoint]
save_every = 50
keep_latest = 3
save_dir = "weights"

[metrics]
log_every = 10